setlocal
set TOPDIR=%~dp0
set PYTHONPATH=%TOPDIR%;%TOPDIR%/src;%PYTHONPATH%
set PYTHONIOENCODING=UTF-8
set PYTHONUNBUFFERED=1
set PROGRAM=%1
set PYTHON=python

%PYTHON% %PROGRAM% %2 %3 %4 %5 %6 %7 %8 %9
endlocal